# Generated by Django 4.0.3 on 2022-03-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('G', 'General'), ('S', 'Sports'), ('Y', 'Year Level')], default='G', max_length=1)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('last_sent', models.DateTimeField()),
                ('is_subscribed', models.BooleanField()),
                ('subscribed_tags', models.ManyToManyField(to='notices.noticetag')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=1000)),
                ('body', models.CharField(max_length=10000)),
                ('teacher', models.CharField(max_length=50)),
                ('meeting_location', models.CharField(max_length=50, null=True)),
                ('meeting_time', models.DateTimeField(null=True)),
                ('tags', models.ManyToManyField(to='notices.noticetag')),
            ],
        ),
    ]
