# Generated by Django 4.0.3 on 2022-03-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_alter_subscriber_is_subscribed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=False)),
                ('issue_date', models.DateField()),
                ('overrides_json', models.CharField(default='{}', max_length=500000)),
                ('notices', models.ManyToManyField(to='notices.notice')),
            ],
        ),
    ]
