# Generated by Django 4.0.3 on 2022-03-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0003_subscriber_is_admin_newsletter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='notice',
            name='event_time',
            field=models.DateTimeField(null=True),
        ),
    ]
