# Generated by Django 4.0.3 on 2022-03-04 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0005_notice_datetime_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='event_time',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='noticetag',
            name='type',
            field=models.CharField(choices=[('G', 'General'), ('S', 'Sports'), ('E', 'Events'), ('Y', 'Year Level'), ('C', 'Clubs')], default='G', max_length=1),
        ),
    ]
