# Generated by Django 4.0.3 on 2022-03-05 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0007_rename_subscribed_tags_subscriber_unsubscribed_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
